# Generated by Django 3.0.5 on 2021-06-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='regAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
